window.TAICHUNG_YOUTH_BASE_DATA = {
  generatedAt: "2026-07-05T00:00:00+08:00",
  evidenceMonth: "2026-07",
  driveRootUrl: "https://drive.google.com/drive/folders/0AN_42cvSSGfMUk9PVA",
  sources: [
    {
      name: "青創基地每週空間回報",
      type: "Google Sheet",
      url: "https://docs.google.com/spreadsheets/d/1k7hU4dBymaM31XNDWD5fbiHOlHlF3Xjfxh0ooAgvTaA/edit",
      modifiedTime: "2026-06-29T00:08:05.973Z",
      status: "watch",
      note: "7/6、7/13、7/20 尚待後續填寫，適合做每週提醒。",
    },
    {
      name: "勞工局新創基地_工作執行進度表.xlsx",
      type: "Excel",
      url: "https://docs.google.com/spreadsheets/d/1te31KWIfonRdR-zBQcC-ejfIr5hYWeli/edit",
      modifiedTime: "2026-05-25T23:55:07.000Z",
      status: "watch",
      note: "核心工項表仍有主責、合約、月報繳交日等待確認欄位。",
    },
    {
      name: "摘星計畫區房舍修繕費用統計表.xlsx",
      type: "Excel",
      url: "https://docs.google.com/spreadsheets/d/1pEacGjwdO_esmTOr2MuALYuUOEz7MHFE/edit",
      modifiedTime: "2026-06-30T03:34:30.021Z",
      status: "ok",
      note: "已可用於掌握修繕總經費、已用與剩餘額度。",
    },
    {
      name: "成果報告資料整理",
      type: "Drive Folder",
      url: "https://drive.google.com/drive/folders/114qmRGC4XnNNkQF0dnKhTL4hgWTsh7L9",
      modifiedTime: "2026-02-03T04:57:40.708Z",
      status: "watch",
      note: "01-23 月報佐證分類完整，需改用子資料夾更新狀態判斷缺漏。",
    },
    {
      name: "3. 交接相關電子檔（處理中）",
      type: "Drive Folder",
      url: "https://drive.google.com/drive/folders/16xbWyxkGhHFMsavvcotPxvZjR_dWLvTi",
      modifiedTime: "2025-12-31T07:31:58.373Z",
      status: "risk",
      note: "含進駐青年個資、聯絡方式、租約與交接清單；前端只顯示去識別摘要。",
    },
    {
      name: "115年第一次進駐店家",
      type: "Drive Folder",
      url: "https://drive.google.com/drive/folders/1eojhF0KnfaTRFr70ZMaoBD2sWsoUrcNO",
      modifiedTime: "2026-05-12T05:51:20.823Z",
      status: "risk",
      note: "包含身分證、存摺、商登與稅登等敏感附件，不放入公開頁快照。",
    },
  ],
  workItems: [
    { name: "專案啟動與合約條件確認", category: "行政控管", progress: 0, status: "risk", owner: "待填", schedule: "待確認", note: "尚未取得正式合約書與工作計畫書。" },
    { name: "場域巡視與值班管理", category: "場域營運", progress: 30, status: "watch", owner: "待填", schedule: "每月", note: "需補各月份是否已完整收齊，並依月報格式整理。" },
    { name: "專案人員出勤與工作日誌", category: "行政控管", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "建議每月固定於月報前檢核缺漏。" },
    { name: "行政庶務及問題排除", category: "行政服務", progress: 30, status: "watch", owner: "待填", schedule: "每月", note: "需整理每月問題類型與處理結果，供成果報告使用。" },
    { name: "青年進駐管理情形", category: "進駐管理", progress: 40, status: "watch", owner: "待填", schedule: "每月", note: "可依審計新村與光復新村分區彙整。" },
    { name: "訪視紀錄與輔導追蹤", category: "輔導服務", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "建議增加問題、建議、下次追蹤欄位。" },
    { name: "一般民眾服務與參訪紀錄", category: "公共服務", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "需確認參訪申請 Google 表單與實際紀錄是否同步。" },
    { name: "空間使用審查與活動辦理", category: "空間管理", progress: 25, status: "watch", owner: "待填", schedule: "依申請", note: "建議建立申請、審查、核定、活動後成果四段追蹤。" },
    { name: "會議紀錄與審核證明", category: "行政控管", progress: 30, status: "watch", owner: "待填", schedule: "依會議", note: "可補會議主題、決議、後續追蹤事項。" },
    { name: "網站、社群與一站式入口網內容檢核", category: "行銷宣傳", progress: 35, status: "watch", owner: "待填", schedule: "每月", note: "每月整理貼文數、觸及/互動、官網更新項目。" },
    { name: "青創基地修繕與環境維護", category: "場域營運", progress: 30, status: "watch", owner: "待填", schedule: "每月", note: "需將審計新村與光復新村分開統計。" },
    { name: "競爭型獎勵補助申請彙整", category: "獎補助管理", progress: 35, status: "watch", owner: "待填", schedule: "每月/依申請", note: "建議建立案件流水表，追蹤申請人、空間、金額、審查結果。" },
    { name: "勞動IN台中店家與媒體露出彙整", category: "行銷宣傳", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "補連結、截圖、發布日期、觸及成效。" },
    { name: "光復新村遊客滿意度調查", category: "成效評估", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "固定輸出樣本數、滿意度平均、主要建議。" },
    { name: "每月成果報告與年度結案", category: "報告交付", progress: 20, status: "risk", owner: "待填", schedule: "每月/期末", note: "待正式合約確認繳交日期與份數。" },
  ],
  evidenceCategories: [
    "01巡視紀錄", "02專案人員出勤表", "03專案人員工作日誌", "04行政庶務及問題排除", "05參訪紀錄及基地臨時緊急事件", "06訪視紀錄表", "07一般民眾服務紀錄表", "08光復新村庭院空間使用審查申請", "09光復新村體驗教室使用審查", "10結案報告提交信件截圖", "11會議記錄審核證明", "12青年進駐管理情形表", "13青創基地修繕項目", "14官方網站、FB更新狀況", "15青年一站式創業入口網內容檢核", "16競爭型獎勵補助申請彙整", "17勞動IN台中店家彙整", "18青創基地新聞媒體主動露出彙整", "19光復新村遊客滿意度調查", "20清潔紀錄", "21保全紀錄", "22光復新村全區消毒、除草紀錄", "23清潔、保全工作日誌"
  ].map((name, index) => ({
    name,
    status: index < 3 ? "risk" : index < 16 ? "watch" : "ok",
    note: index < 16 ? "待由 Drive 子資料夾更新時間自動判斷本月是否收齊。" : "已有固定分類，後續以月份資料更新狀態。",
  })),
  spaceReport: {
    week: "2026-06-29",
    nextDue: "2026-07-06",
    guangfu: { available: 46, occupied: 42, vacant: 4, vacantUnits: "F5+6、F7、F15+16、G31" },
    shenji: { available: 26, occupied: 24, vacant: 2, vacantUnits: "B10、D18" },
    total: { occupied: 65, vacant: 6, visits: "無" },
  },
  repairBudget: {
    updated: "2026-06-30",
    total: 1200000,
    spent: 729960,
    balance: 470040,
    items: [
      { date: "115/06/29", base: "光復新村", item: "和平路13號前後門、門柱加固、門片換新", amount: 26000 },
      { date: "115/06/29", base: "光復新村", item: "和平路7號廢水排水管配管至排水溝下游防止倒灌", amount: 10000 },
      { date: "115/06/29", base: "光復新村", item: "新生路110號後門修繕", amount: 6000 },
      { date: "115/06/26", base: "光復新村", item: "F13+14 1F庭院紅色鐵門", amount: 12000 },
      { date: "115/05/14", base: "光復新村", item: "全區樹木修剪", amount: 78750 },
    ],
  },
  cases: [
    { title: "正式合約書與工作計畫書", type: "行政控管", status: "risk", due: "待確認", note: "取得後需更新 KPI、期限、經費與正式交付物。" },
    { title: "每月成果報告繳交日與核銷格式", type: "報告交付", status: "risk", due: "待確認", note: "目前以成果資料夾分類先行檢核，正式期限需補入。" },
    { title: "空間使用申請四段追蹤", type: "空間管理", status: "watch", due: "依申請", note: "申請、審查、核定、活動後成果需要流水表。" },
    { title: "競爭型補助案件流水表", type: "獎補助管理", status: "watch", due: "每月", note: "追蹤申請人、空間、金額、審查結果與核定後成果。" },
    { title: "青年座談反映事項列管", type: "問題列管", status: "watch", due: "持續", note: "交接清單內已有持續列管與建議解除列管資料，需拆成去識別摘要。" },
  ],
};
