window.TAICHUNG_YOUTH_BASE_DATA = {
  generatedAt: "2026-07-05T00:00:00+08:00",
  evidenceMonth: "2026-07",
  driveRootUrl: "https://drive.google.com/drive/folders/0AN_42cvSSGfMUk9PVA",
  sources: [
    {
      name: "勞工局契約書_內容+頁碼_v2",
      type: "Google Doc / PDF",
      url: "https://docs.google.com/document/d/1NUn3uuM5y4Qent2MwA6jAB3QA59Sd9JH9EFyXi6UP4M/edit",
      modifiedTime: "2026-01-19T02:25:03.772Z",
      status: "ok",
      note: "115年度青創基地創業服務平台委託服務案合約與邀標書彙整版，作為履約對照基準。",
    },
    {
      name: "青創基地每週空間回報",
      type: "Google Sheet",
      url: "https://docs.google.com/spreadsheets/d/1k7hU4dBymaM31XNDWD5fbiHOlHlF3Xjfxh0ooAgvTaA/edit",
      modifiedTime: "2026-06-29T00:08:05.973Z",
      status: "watch",
      note: "7/6、7/13、7/20 尚待後續填寫，適合做每週提醒。",
    },
    {
      name: "勞工局新創基地_工作執行進度表.xlsx",
      type: "Excel",
      url: "https://docs.google.com/spreadsheets/d/1te31KWIfonRdR-zBQcC-ejfIr5hYWeli/edit",
      modifiedTime: "2026-05-25T23:55:07.000Z",
      status: "watch",
      note: "核心工項表仍有主責、合約、月報繳交日等待確認欄位。",
    },
    {
      name: "摘星計畫區房舍修繕費用統計表.xlsx",
      type: "Excel",
      url: "https://docs.google.com/spreadsheets/d/1pEacGjwdO_esmTOr2MuALYuUOEz7MHFE/edit",
      modifiedTime: "2026-06-30T03:34:30.021Z",
      status: "ok",
      note: "已可用於掌握修繕總經費、已用與剩餘額度。",
    },
    {
      name: "成果報告資料整理",
      type: "Drive Folder",
      url: "https://drive.google.com/drive/folders/114qmRGC4XnNNkQF0dnKhTL4hgWTsh7L9",
      modifiedTime: "2026-02-03T04:57:40.708Z",
      status: "watch",
      note: "01-23 月報佐證分類完整，需改用子資料夾更新狀態判斷缺漏。",
    },
    {
      name: "3. 交接相關電子檔（處理中）",
      type: "Drive Folder",
      url: "https://drive.google.com/drive/folders/16xbWyxkGhHFMsavvcotPxvZjR_dWLvTi",
      modifiedTime: "2025-12-31T07:31:58.373Z",
      status: "risk",
      note: "含進駐青年個資、聯絡方式、租約與交接清單；前端只顯示去識別摘要。",
    },
    {
      name: "115年第一次進駐店家",
      type: "Drive Folder",
      url: "https://drive.google.com/drive/folders/1eojhF0KnfaTRFr70ZMaoBD2sWsoUrcNO",
      modifiedTime: "2026-05-12T05:51:20.823Z",
      status: "risk",
      note: "包含身分證、存摺、商登與稅登等敏感附件，不放入公開頁快照。",
    },
  ],
  workItems: [
    { name: "專案啟動與合約條件確認", category: "行政控管", progress: 0, status: "risk", owner: "待填", schedule: "待確認", note: "尚未取得正式合約書與工作計畫書。" },
    { name: "場域巡視與值班管理", category: "場域營運", progress: 30, status: "watch", owner: "待填", schedule: "每月", note: "需補各月份是否已完整收齊，並依月報格式整理。" },
    { name: "專案人員出勤與工作日誌", category: "行政控管", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "建議每月固定於月報前檢核缺漏。" },
    { name: "行政庶務及問題排除", category: "行政服務", progress: 30, status: "watch", owner: "待填", schedule: "每月", note: "需整理每月問題類型與處理結果，供成果報告使用。" },
    { name: "青年進駐管理情形", category: "進駐管理", progress: 40, status: "watch", owner: "待填", schedule: "每月", note: "可依審計新村與光復新村分區彙整。" },
    { name: "訪視紀錄與輔導追蹤", category: "輔導服務", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "建議增加問題、建議、下次追蹤欄位。" },
    { name: "一般民眾服務與參訪紀錄", category: "公共服務", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "需確認參訪申請 Google 表單與實際紀錄是否同步。" },
    { name: "空間使用審查與活動辦理", category: "空間管理", progress: 25, status: "watch", owner: "待填", schedule: "依申請", note: "建議建立申請、審查、核定、活動後成果四段追蹤。" },
    { name: "會議紀錄與審核證明", category: "行政控管", progress: 30, status: "watch", owner: "待填", schedule: "依會議", note: "可補會議主題、決議、後續追蹤事項。" },
    { name: "網站、社群與一站式入口網內容檢核", category: "行銷宣傳", progress: 35, status: "watch", owner: "待填", schedule: "每月", note: "每月整理貼文數、觸及/互動、官網更新項目。" },
    { name: "青創基地修繕與環境維護", category: "場域營運", progress: 30, status: "watch", owner: "待填", schedule: "每月", note: "需將審計新村與光復新村分開統計。" },
    { name: "競爭型獎勵補助申請彙整", category: "獎補助管理", progress: 35, status: "watch", owner: "待填", schedule: "每月/依申請", note: "建議建立案件流水表，追蹤申請人、空間、金額、審查結果。" },
    { name: "勞動IN台中店家與媒體露出彙整", category: "行銷宣傳", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "補連結、截圖、發布日期、觸及成效。" },
    { name: "光復新村遊客滿意度調查", category: "成效評估", progress: 25, status: "watch", owner: "待填", schedule: "每月", note: "固定輸出樣本數、滿意度平均、主要建議。" },
    { name: "每月成果報告與年度結案", category: "報告交付", progress: 20, status: "risk", owner: "待填", schedule: "每月/期末", note: "待正式合約確認繳交日期與份數。" },
  ],
  evidenceCategories: [
    "01巡視紀錄", "02專案人員出勤表", "03專案人員工作日誌", "04行政庶務及問題排除", "05參訪紀錄及基地臨時緊急事件", "06訪視紀錄表", "07一般民眾服務紀錄表", "08光復新村庭院空間使用審查申請", "09光復新村體驗教室使用審查", "10結案報告提交信件截圖", "11會議記錄審核證明", "12青年進駐管理情形表", "13青創基地修繕項目", "14官方網站、FB更新狀況", "15青年一站式創業入口網內容檢核", "16競爭型獎勵補助申請彙整", "17勞動IN台中店家彙整", "18青創基地新聞媒體主動露出彙整", "19光復新村遊客滿意度調查", "20清潔紀錄", "21保全紀錄", "22光復新村全區消毒、除草紀錄", "23清潔、保全工作日誌"
  ].map((name, index) => ({
    name,
    status: index < 3 ? "risk" : index < 16 ? "watch" : "ok",
    note: index < 16 ? "待由 Drive 子資料夾更新時間自動判斷本月是否收齊。" : "已有固定分類，後續以月份資料更新狀態。",
  })),
  spaceReport: {
    week: "2026-06-29",
    nextDue: "2026-07-06",
    guangfu: { available: 46, occupied: 42, vacant: 4, vacantUnits: "F5+6、F7、F15+16、G31" },
    shenji: { available: 26, occupied: 24, vacant: 2, vacantUnits: "B10、D18" },
    total: { occupied: 65, vacant: 6, visits: "無" },
  },
  repairBudget: {
    updated: "2026-06-30",
    total: 1200000,
    spent: 729960,
    balance: 470040,
    items: [
      { date: "115/06/29", base: "光復新村", item: "和平路13號前後門、門柱加固、門片換新", amount: 26000 },
      { date: "115/06/29", base: "光復新村", item: "和平路7號廢水排水管配管至排水溝下游防止倒灌", amount: 10000 },
      { date: "115/06/29", base: "光復新村", item: "新生路110號後門修繕", amount: 6000 },
      { date: "115/06/26", base: "光復新村", item: "F13+14 1F庭院紅色鐵門", amount: 12000 },
      { date: "115/05/14", base: "光復新村", item: "全區樹木修剪", amount: 78750 },
    ],
  },
  cases: [
    { title: "第2期款期中資料補正", type: "付款/驗收", status: "risk", due: "2026-07-10", note: "合約要求 115/7/10 前檢附期中報告及經費支出明細表；需逐項對照 A-K 子項目佐證。" },
    { title: "每月成果報告固定期限", type: "報告交付", status: "risk", due: "每月10日前", note: "合約要求自 2 月起每月 10 日前提送前一月執行事項予機關留存。" },
    { title: "空間使用申請四段追蹤", type: "空間管理", status: "watch", due: "依申請", note: "申請、審查、核定、活動後成果需要流水表。" },
    { title: "競爭型補助案件流水表", type: "獎補助管理", status: "watch", due: "每月", note: "追蹤申請人、空間、金額、審查結果與核定後成果。" },
    { title: "青年座談反映事項列管", type: "問題列管", status: "watch", due: "持續", note: "交接清單內已有持續列管與建議解除列管資料，需拆成去識別摘要。" },
  ],
  contract: {
    title: "115年度青創基地創業服務平台委託服務案",
    agency: "臺中市政府勞工局",
    vendor: "在一起地域循環設計有限公司",
    amount: 8523000,
    period: "2026-01-01 至 2026-12-31",
    sourceUrl: "https://docs.google.com/document/d/1NUn3uuM5y4Qent2MwA6jAB3QA59Sd9JH9EFyXi6UP4M/edit",
    folderUrl: "https://drive.google.com/drive/folders/1nlUYx03E6GctEoCXiNVaNsaZRGqS2bjd",
  },
  contractRequirements: [
    {
      id: "PAY-01",
      source: "契約第5條/經費預算",
      title: "第1期款付款條件",
      due: "2026-02-10",
      status: "ok",
      category: "付款節點",
      requirement: "函報專案辦公室3名人員名單、辦公室地點、工作分配、學經歷、勞保資料、保全/清潔人員佐證，並完成第1次工作會議。",
      evidence: "人員名單、勞保明細、保全/清潔人員名單、第1次工作會議紀錄、發票或收據。",
      dashboardMapping: "Drive 更新、月報佐證、案件列管",
    },
    {
      id: "PAY-02",
      source: "契約第5條/經費預算",
      title: "第2期款期中報告",
      due: "2026-07-10",
      status: "risk",
      category: "付款節點",
      requirement: "檢附期中報告一式及經費支出明細表，內容需含 A-K 子項目履約佐證。",
      evidence: "期中報告、經費支出明細、簽到退表、工作日誌、查訪營運紀錄、未達標清冊、進離駐/修繕/借用/訪視/會議/補助/活動/網站/滿意度/民眾反映/保全/清潔等佐證。",
      dashboardMapping: "合約對照、月報佐證、工項進度、修繕經費、空間營運",
    },
    {
      id: "PAY-03",
      source: "契約第5條/經費預算",
      title: "第3期款期末與交接",
      due: "2026-12-10",
      status: "watch",
      category: "付款節點",
      requirement: "115/11/30 前達成所有委託事項，115/12/10 前檢附期末年度報告、未來規劃方向建議、經費支出明細、工作進度交接清冊與交接日期。",
      evidence: "期末報告、未來規劃建議、經費明細、交接清冊、交接紀錄、12/15-12/31 與次年度廠商交接佐證。",
      dashboardMapping: "合約對照、案件列管、主管摘要",
    },
    {
      id: "RPT-01",
      source: "邀標書/實施內容",
      title: "每月成果報告",
      due: "每月10日前",
      status: "risk",
      category: "報告交付",
      requirement: "自2月起每月10日前提送前1個月執行事項予機關留存。",
      evidence: "每月成果報告、月報佐證 01-23 分類、函送或提交紀錄。",
      dashboardMapping: "月報佐證、主管摘要",
    },
    {
      id: "OPS-01",
      source: "契約第5條第2期款B-C",
      title: "基地營運與進駐管理",
      due: "每月",
      status: "watch",
      category: "場域營運",
      requirement: "審計新村與光復新村查訪營運紀錄、營運未達標清冊、進駐人數計算、進/離駐進度、營運異常、行政違規、修繕、年度考核、空間借用與訪視紀錄。",
      evidence: "每週空間回報、進駐管理表、查訪紀錄、未達標清冊、修繕紀錄、借用審查、訪視紀錄。",
      dashboardMapping: "空間營運、工項進度、月報佐證",
    },
    {
      id: "MTG-01",
      source: "邀標書/會議要求",
      title: "工作會議與會議紀錄",
      due: "1月、4月、7月、10月；會後3日內",
      status: "watch",
      category: "會議管考",
      requirement: "每3個月舉辦1次工作會議，針對進度、維運、特殊事件與活動討論；會議結束後3日內提供會議紀錄並併入月報。",
      evidence: "議程、簽到、會議紀錄、決議列管表、月報收錄證明。",
      dashboardMapping: "案件列管、月報佐證、主管摘要",
    },
    {
      id: "MTG-02",
      source: "邀標書/青年座談會",
      title: "青年座談會",
      due: "上、下半年各1次；會後3日內",
      status: "watch",
      category: "會議管考",
      requirement: "每次座談會應含光復新村及審計新村各1場；會前提交議程與前次追蹤列管更新，會後3日內提供會議紀錄。",
      evidence: "議程、前次列管更新、簽到、會議紀錄、追蹤列管表。",
      dashboardMapping: "案件列管、月報佐證",
    },
    {
      id: "MKT-01",
      source: "邀標書/基地活動與推廣",
      title: "基地行銷活動",
      due: "年度至少3場；活動前40日送審",
      status: "watch",
      category: "行銷推廣",
      requirement: "至少3場基地行銷活動，每場參與人數至少2,000人次；活動規劃與主視覺應於辦理首日前40日提送機關審查。",
      evidence: "活動企劃、主視覺送審紀錄、參與人次統計、活動照片、成果報告。",
      dashboardMapping: "工項進度、月報佐證、主管摘要",
    },
    {
      id: "MKT-02",
      source: "邀標書/網站社群維護",
      title: "官網與社群更新",
      due: "每週1至2次",
      status: "watch",
      category: "行銷推廣",
      requirement: "定期更新臺中市青年一站式創業入口網與 FB 粉絲專頁，每週至少1至2次，並上傳活動及參訪接待照片。",
      evidence: "官網截圖、FB貼文截圖、每月檢核表、貼文連結與更新日期。",
      dashboardMapping: "月報佐證、Drive 更新",
    },
    {
      id: "VIS-01",
      source: "邀標書/參訪接待",
      title: "機關團體基地參訪",
      due: "依申請；參訪後3日內",
      status: "watch",
      category: "公共服務",
      requirement: "受理參訪申請、建置 SOP、製作介紹簡報及流程安排；參訪後3日內上傳照片至官網及 FB。",
      evidence: "參訪申請、SOP、簡報、流程表、照片上傳證明、參訪紀錄。",
      dashboardMapping: "月報佐證、案件列管",
    },
    {
      id: "SEC-01",
      source: "邀標書/保全服務",
      title: "光復新村夜間保全",
      due: "每日19:00-07:00",
      status: "watch",
      category: "保全清潔",
      requirement: "夜間保全駐守，至少6處巡邏紀錄器，每日執勤期間至少6次巡邏簽到，填寫工作日誌及出勤紀錄。",
      evidence: "保全簽到單、巡檢督導紀錄、工作日誌、出勤紀錄、異常通報。",
      dashboardMapping: "月報佐證",
    },
    {
      id: "CLN-01",
      source: "邀標書/環境清潔維護",
      title: "光復新村園區清潔維護",
      due: "每日/年度定期",
      status: "watch",
      category: "保全清潔",
      requirement: "至少1名清潔人力；每日清掃與廁所清潔；公共區域消毒12次、除草18次、水溝疏通5次。",
      evidence: "清潔簽到、工作日誌、消毒紀錄、除草紀錄、水溝疏通紀錄、照片。",
      dashboardMapping: "月報佐證、修繕經費",
    },
    {
      id: "IP-01",
      source: "邀標書/智慧財產權",
      title: "成果著作權與素材授權",
      due: "交付前",
      status: "watch",
      category: "法遵",
      requirement: "履約完成之著作財產權由機關取得；文字、影像、圖片、影片等素材不得侵權，第三方素材需取得合法授權。",
      evidence: "原始檔、授權證明、素材來源表、成果交付清單。",
      dashboardMapping: "案件列管、主管摘要",
    },
  ],
};
